[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/04_layernorm.ipynb)

# 🟡 Medium: Implement LayerNorm

Implement **Layer Normalization** from scratch.

$$\text{LayerNorm}(x) = \gamma \cdot \frac{x - \mu}{\sqrt{\sigma^2 + \epsilon}} + \beta$$

where $\mu$ and $\sigma^2$ are computed over the **last dimension**.

### Signature
```python
def my_layer_norm(
    x: torch.Tensor,      # input
    gamma: torch.Tensor,   # scale (same size as last dim)
    beta: torch.Tensor,    # shift (same size as last dim)
    eps: float = 1e-5
) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `F.layer_norm` or `torch.nn.LayerNorm`
- Normalize over the last dimension only
- Must support autograd

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.5 MB/s eta 0:00:00


In [6]:
import torch
import math

In [56]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_layer_norm(x, gamma, beta, eps=1e-5):
    sigma = torch.var(x, dim=-1, keepdim=True, unbiased=False)
    mu = torch.mean(x, dim=-1, keepdim=True)
    return gamma*(x-mu)/torch.sqrt(sigma+eps)+beta

In [59]:
# 🧪 Debug
x = torch.randn(2, 8)
gamma = torch.ones(8)
beta = torch.zeros(8)

out = my_layer_norm(x, gamma, beta)
ref = torch.nn.functional.layer_norm(x, [8], gamma, beta)

print("Your output mean:", out.mean(dim=-1))   # should be ~0
print("Your output std: ", out.std(dim=-1))     # should be ~1
print("Match ref?      ", torch.allclose(out, ref, atol=1e-4))

tensor([[-0.4091,  0.2392, -0.9899,  2.2235, -0.5419, -0.6812,  1.8192,  0.6201],
        [ 0.8231, -1.4937,  0.2379,  0.9658,  1.4530,  1.0937,  0.2570,  2.7918]])
tensor([[1.2438],
        [1.2963]]) tensor([[0.2850],
        [0.7661]])
Your output mean: tensor([ 0.0000e+00, -1.4901e-08])
Your output std:  tensor([1.0690, 1.0690])
Match ref?       True


In [58]:
# ✅ SUBMIT
from torch_judge import check
check("layernorm")


🧪 Testing: Implement LayerNorm (Medium)
──────────────────────────────────────────────────
tensor([[[-0.7843, -0.7331,  2.3994, -0.4529,  1.4613,  0.7238,  0.2518,
          -0.5857],
         [-0.3195,  1.1248,  0.5207,  0.2133, -0.8244,  0.4216, -1.4325,
          -0.2384],
         [-1.4785,  0.6890,  0.8752, -0.6449, -0.1168,  0.0512,  0.0470,
          -0.7451]],

        [[ 1.2767,  0.9710,  1.2947,  1.1808,  0.8561,  0.0312,  0.7963,
          -1.2634],
         [-0.8583,  1.3469, -0.1662, -0.5406, -1.0749,  0.7594,  0.9973,
          -0.3301],
         [-1.3353,  0.1220,  0.4716, -1.4970, -0.5343, -0.4825, -0.4315,
           0.5719]]])
tensor([[[1.1913],
         [0.5768],
         [0.5247]],

        [[0.6626],
         [0.7130],
         [0.5100]]]) tensor([[[ 0.2850],
         [-0.0668],
         [-0.1654]],

        [[ 0.6429],
         [ 0.0167],
         [-0.3894]]])
  ✅ [1/3] Shape and basic behavior (5.7ms)
tensor([[ 1.1655, -1.2967, -2.3085,  0.6503, -0.1642, -1.0542